name: Main Application PipeLine
on: push

jobs:
  Deploy_Job:
    # Right: 'uses' is placed directly under the job name
    uses: souravgit2021/shared-lib-test/.github/workflows/hello-reusable.yml@main